export const auth = {
  LOGIN: "LOGIN",
  LOGIN_LOADING: "LOGIN_LOADING",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_ERROR: "LOGIN_ERROR",
  LOGIN_RESET: "LOGIN_RESET",

  REGISTER: "REGISTER",
  REGISTER_LOADING: "REGISTER_LOADING",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_ERROR: "REGISTER_ERROR",
  REGISTER_RESET: "REGISTER_RESET",
};
