export const leave = {
  // CREATE
  CREATE_LEAVE: "CREATE_LEAVE",
  CREATE_LEAVE_LOADING: "CREATE_LEAVE_LOADING",
  CREATE_LEAVE_SUCCESS: "CREATE_LEAVE_SUCCESS",
  CREATE_LEAVE_ERROR: "CREATE_LEAVE_ERROR",
  CREATE_LEAVE_RESET: "CREATE_LEAVE_RESET",

  // GET
  GET_LEAVE: "GET_LEAVE",
  GET_LEAVE_LOADING: "GET_LEAVE_LOADING",
  GET_LEAVE_SUCCESS: "GET_LEAVE_SUCCESS",
  GET_LEAVE_ERROR: "GET_LEAVE_ERROR",
  GET_LEAVE_RESET: "GET_LEAVE_RESET",

  // GET
  GET_LEAVE_WITH_FILTER: "GET_LEAVE_WITH_FILTER",
  GET_LEAVE_WITH_FILTER_LOADING: "GET_LEAVE_WITH_FILTER_LOADING",
  GET_LEAVE_WITH_FILTER_SUCCESS: "GET_LEAVE_WITH_FILTER_SUCCESS",
  GET_LEAVE_WITH_FILTER_ERROR: "GET_LEAVE_WITH_FILTER_ERROR",
  GET_LEAVE_WITH_FILTER_RESET: "GET_LEAVE_WITH_FILTER_RESET",

  // UPDATE
  UPDATE_LEAVE: "UPDATE_LEAVE",
  UPDATE_LEAVE_LOADING: "UPDATE_LEAVE_LOADING",
  UPDATE_LEAVE_SUCCESS: "UPDATE_LEAVE_SUCCESS",
  UPDATE_LEAVE_ERROR: "UPDATE_LEAVE_ERROR",
  UPDATE_LEAVE_RESET: "UPDATE_LEAVE_RESET",
};
