export const candidate = {
  ADD_CANDIDATE: "ADD_CANDIDATE",
  ADD_CANDIDATE_LOADING: "ADD_CANDIDATE_LOADING",
  ADD_CANDIDATE_SUCCESS: "ADD_CANDIDATE_SUCCESS",
  ADD_CANDIDATE_ERROR: "ADD_CANDIDATE_ERROR",
  ADD_CANDIDATE_RESET: "ADD_CANDIDATE_RESET",

  GET_CANDIDATE: "GET_CANDIDATE",
  GET_CANDIDATE_LOADING: "GET_CANDIDATE_LOADING",
  GET_CANDIDATE_SUCCESS: "GET_CANDIDATE_SUCCESS",
  GET_CANDIDATE_ERROR: "GET_CANDIDATE_ERROR",
  GET_CANDIDATE_RESET: "GET_CANDIDATE_RESET",

  UPDATE_CANDIDATE: "UPDATE_CANDIDATE",
  UPDATE_CANDIDATE_LOADING: "UPDATE_CANDIDATE_LOADING",
  UPDATE_CANDIDATE_SUCCESS: "UPDATE_CANDIDATE_SUCCESS",
  UPDATE_CANDIDATE_ERROR: "UPDATE_CANDIDATE_ERROR",
  UPDATE_CANDIDATE_RESET: "UPDATE_CANDIDATE_RESET",

  DELETE_CANDIDATE: "DELETE_CANDIDATE",
  DELETE_CANDIDATE_LOADING: "DELETE_CANDIDATE_LOADING",
  DELETE_CANDIDATE_SUCCESS: "DELETE_CANDIDATE_SUCCESS",
  DELETE_CANDIDATE_ERROR: "DELETE_CANDIDATE_ERROR",
  DELETE_CANDIDATE_RESET: "DELETE_CANDIDATE_RESET",
};
