export const employee = {
  // Get
  GET_EMPLOYEE: "GET_EMPLOYEE",
  GET_EMPLOYEE_LOADING: "GET_EMPLOYEE_LOADING",
  GET_EMPLOYEE_SUCCESS: "GET_EMPLOYEE_SUCCESS",
  GET_EMPLOYEE_ERROR: "GET_EMPLOYEE_ERROR",
  GET_EMPLOYEE_RESET: "GET_EMPLOYEE_RESET",

  // Update
  UPDATE_EMPLOYEE: "UPDATE_EMPLOYEE",
  UPDATE_EMPLOYEE_LOADING: "UPDATE_EMPLOYEE_LOADING",
  UPDATE_EMPLOYEE_SUCCESS: "UPDATE_EMPLOYEE_SUCCESS",
  UPDATE_EMPLOYEE_ERROR: "UPDATE_EMPLOYEE_ERROR",
  UPDATE_EMPLOYEE_RESET: "UPDATE_EMPLOYEE_RESET",

  // Delete
  DELETE_EMPLOYEE: "DELETE_EMPLOYEE",
  DELETE_EMPLOYEE_LOADING: "DELETE_EMPLOYEE_LOADING",
  DELETE_EMPLOYEE_SUCCESS: "DELETE_EMPLOYEE_SUCCESS",
  DELETE_EMPLOYEE_ERROR: "DELETE_EMPLOYEE_ERROR",
  DELETE_EMPLOYEE_RESET: "DELETE_EMPLOYEE_RESET",
};
